definitions:
  models.AccountIdDetail:
    properties:
      adjustment_guiding:
        type: boolean
      company:
        type: string
      dashboard:
        type: boolean
      email:
        type: string
      id:
        type: integer
      parameter_failure_pediction:
        type: boolean
      process_status_analysis:
        type: boolean
      spc:
        type: boolean
    type: object
  models.Err:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /account:
    post:
      consumes:
      - application/json
      description: 新增帳號資訊
      parameters:
      - description: Account Detail
        in: body
        name: detail
        required: true
        schema:
          $ref: '#/definitions/models.AccountIdDetail'
      produces:
      - application/json
      responses:
        "200":
          description: Account Id
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
      summary: add vip account detail
      tags:
      - API
  /account/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除帳號資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
      summary: delete vip account detail
      tags:
      - API
    get:
      consumes:
      - application/json
      description: 查詢帳號資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountIdDetail'
        "400":
          description: '{"error":"account not exist"}'
          schema:
            $ref: '#/definitions/models.Err'
      summary: get vip account detail
      tags:
      - API
    put:
      consumes:
      - application/json
      description: 修改帳號資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Account Detail
        in: body
        name: detail
        required: true
        schema:
          $ref: '#/definitions/models.AccountIdDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
      summary: edit vip account detail
      tags:
      - API
  /accounts:
    get:
      consumes:
      - application/json
      description: 查詢所有帳號資訊
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AccountIdDetail'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Err'
      summary: get all vip accounts detail
      tags:
      - API
  /customer/account:
    get:
      consumes:
      - application/json
      description: 客戶查詢帳號資訊
      parameters:
      - description: Account Email
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccountIdDetail'
        "400":
          description: '{"error":"account not exist"}'
          schema:
            $ref: '#/definitions/models.Err'
      summary: customer get vip account detail
      tags:
      - Customer API
swagger: "2.0"
